Add sample CoC
diversidade/diversidade.github.io pull request #11
Opened 2017-09-15 22:24 UTC by giggio

2017-09-25 16:26 UTC, eduardojmatos requested changes
Só uma formatação e um typo no final.

Sobre o conteúdo, está 100% cara, muito bom!

2017-09-25 16:26 UTC, eduardojmatos commented on _pages/exemplo-codigo-de-conduta.markdown
> +sigam à risca. Você pode utilizado o nosso na íntegra ou em partes, de acordo
"Você pode utilizar o nosso"

2017-09-25 16:26 UTC, eduardojmatos commented on _pages/exemplo-codigo-de-conduta.markdown
> +você precisa substituir estão marcados entre colchetes `[]`.
Só questão de formatação, mas as linhas estão quebrando sem ser parágrafo

2017-09-26 22:47 UTC, giggio commented on _pages/exemplo-codigo-de-conduta.markdown
> +você precisa substituir estão marcados entre colchetes `[]`.
@eduardojmatos O markdown não quebra linha a não ser que você pule linha. Isso permite o uso de editores de textos em telas menores. É padrão no *nix. Gosto de seguir pra md.

Note que a quebra não acontece quando você roda o site:

![image](https://user-images.githubusercontent.com/334958/30887802-6767d9a0-a2f3-11e7-8f93-84b5024498b8.png)

2017-09-26 22:47 UTC, giggio commented on _pages/exemplo-codigo-de-conduta.markdown
> +sigam à risca. Você pode utilizado o nosso na íntegra ou em partes, de acordo
Corrigido.

2017-09-26 22:49 UTC, eduardojmatos commented on _pages/exemplo-codigo-de-conduta.markdown
> +você precisa substituir estão marcados entre colchetes `[]`.
@giggio sim, era mais pro source ficar sem as quebras. Mas seu ponto faz sentido, aprovando aqui

2017-09-26 22:49 UTC, eduardojmatos approved these changes

2017-09-26 22:59 UTC, merged

2017-09-26 22:59 UTC, giggio commented
@eduardojmatos Ae, estamos no ar! http://diversidade.tech/exemplo-codigo-de-conduta/

2017-09-27 03:28 UTC, eduardojmatos commented
@giggio boa!